rem this file is auto generated by envconf.bat
rem
SET ENV_CONFIG=yes
SET MSVC_HOME="C:\Program Files\Microsoft Visual Studio 9.0"
SET MSVC_VERSION=90
SET JAVA_HOME=C:\Program Files\Java\jdk1.6.0_13
REM SET SDK_HOME=please set the sdk home
REM SET TOOL_HOME=please set the tool home
